Add base url to existing ontology
It caused exception when deploying without base url:
org.eclipse.rdf4j.http.server.ClientHTTPException: MALFORMED DATA: Unable to resolve URIs, no base URI has been set [line 17, column 77]